//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ProjectIIIModel", "FK_tblOrderDetails_tblImages", "tblImages", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ODPP.Data.tblImage), "tblOrderDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ODPP.Data.tblOrderDetail), true)]
[assembly: EdmRelationshipAttribute("ProjectIIIModel", "FK_tblOrder_tblUser", "tblUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ODPP.Data.tblUser), "tblOrder", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ODPP.Data.tblOrder), true)]
[assembly: EdmRelationshipAttribute("ProjectIIIModel", "FK_tblOrderDetails_tblOrder", "tblOrder", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ODPP.Data.tblOrder), "tblOrderDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ODPP.Data.tblOrderDetail), true)]
[assembly: EdmRelationshipAttribute("ProjectIIIModel", "FK_tblOrderDetails_tblSize", "tblSize", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ODPP.Data.tblSize), "tblOrderDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ODPP.Data.tblOrderDetail), true)]

#endregion

namespace ODPP.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ProjectIIIEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ProjectIIIEntities object using the connection string found in the 'ProjectIIIEntities' section of the application configuration file.
        /// </summary>
        public ProjectIIIEntities() : base("name=ProjectIIIEntities", "ProjectIIIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProjectIIIEntities object.
        /// </summary>
        public ProjectIIIEntities(string connectionString) : base(connectionString, "ProjectIIIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ProjectIIIEntities object.
        /// </summary>
        public ProjectIIIEntities(EntityConnection connection) : base(connection, "ProjectIIIEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblAccountBank> tblAccountBanks
        {
            get
            {
                if ((_tblAccountBanks == null))
                {
                    _tblAccountBanks = base.CreateObjectSet<tblAccountBank>("tblAccountBanks");
                }
                return _tblAccountBanks;
            }
        }
        private ObjectSet<tblAccountBank> _tblAccountBanks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblAdmin> tblAdmins
        {
            get
            {
                if ((_tblAdmins == null))
                {
                    _tblAdmins = base.CreateObjectSet<tblAdmin>("tblAdmins");
                }
                return _tblAdmins;
            }
        }
        private ObjectSet<tblAdmin> _tblAdmins;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblImage> tblImages
        {
            get
            {
                if ((_tblImages == null))
                {
                    _tblImages = base.CreateObjectSet<tblImage>("tblImages");
                }
                return _tblImages;
            }
        }
        private ObjectSet<tblImage> _tblImages;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblOrder> tblOrders
        {
            get
            {
                if ((_tblOrders == null))
                {
                    _tblOrders = base.CreateObjectSet<tblOrder>("tblOrders");
                }
                return _tblOrders;
            }
        }
        private ObjectSet<tblOrder> _tblOrders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblOrderDetail> tblOrderDetails
        {
            get
            {
                if ((_tblOrderDetails == null))
                {
                    _tblOrderDetails = base.CreateObjectSet<tblOrderDetail>("tblOrderDetails");
                }
                return _tblOrderDetails;
            }
        }
        private ObjectSet<tblOrderDetail> _tblOrderDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSize> tblSizes
        {
            get
            {
                if ((_tblSizes == null))
                {
                    _tblSizes = base.CreateObjectSet<tblSize>("tblSizes");
                }
                return _tblSizes;
            }
        }
        private ObjectSet<tblSize> _tblSizes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblUser> tblUsers
        {
            get
            {
                if ((_tblUsers == null))
                {
                    _tblUsers = base.CreateObjectSet<tblUser>("tblUsers");
                }
                return _tblUsers;
            }
        }
        private ObjectSet<tblUser> _tblUsers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblAccountBanks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblAccountBanks(tblAccountBank tblAccountBank)
        {
            base.AddObject("tblAccountBanks", tblAccountBank);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblAdmins EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblAdmins(tblAdmin tblAdmin)
        {
            base.AddObject("tblAdmins", tblAdmin);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblImages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblImages(tblImage tblImage)
        {
            base.AddObject("tblImages", tblImage);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblOrders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblOrders(tblOrder tblOrder)
        {
            base.AddObject("tblOrders", tblOrder);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblOrderDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblOrderDetails(tblOrderDetail tblOrderDetail)
        {
            base.AddObject("tblOrderDetails", tblOrderDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSizes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSizes(tblSize tblSize)
        {
            base.AddObject("tblSizes", tblSize);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblUsers(tblUser tblUser)
        {
            base.AddObject("tblUsers", tblUser);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectIIIModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectIIIModel", Name="tblAccountBank")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblAccountBank : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblAccountBank object.
        /// </summary>
        /// <param name="creditCard">Initial value of the CreditCard property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="balance">Initial value of the Balance property.</param>
        public static tblAccountBank CreatetblAccountBank(global::System.Int64 creditCard, global::System.String firstName, global::System.String lastName, global::System.DateTime dateOfBirth, global::System.String phone, global::System.String address, global::System.Double balance)
        {
            tblAccountBank tblAccountBank = new tblAccountBank();
            tblAccountBank.CreditCard = creditCard;
            tblAccountBank.FirstName = firstName;
            tblAccountBank.LastName = lastName;
            tblAccountBank.DateOfBirth = dateOfBirth;
            tblAccountBank.Phone = phone;
            tblAccountBank.Address = address;
            tblAccountBank.Balance = balance;
            return tblAccountBank;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CreditCard
        {
            get
            {
                return _CreditCard;
            }
            set
            {
                if (_CreditCard != value)
                {
                    OnCreditCardChanging(value);
                    ReportPropertyChanging("CreditCard");
                    _CreditCard = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CreditCard");
                    OnCreditCardChanged();
                }
            }
        }
        private global::System.Int64 _CreditCard;
        partial void OnCreditCardChanging(global::System.Int64 value);
        partial void OnCreditCardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.DateTime _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTime value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Balance
        {
            get
            {
                return _Balance;
            }
            set
            {
                OnBalanceChanging(value);
                ReportPropertyChanging("Balance");
                _Balance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Balance");
                OnBalanceChanged();
            }
        }
        private global::System.Double _Balance;
        partial void OnBalanceChanging(global::System.Double value);
        partial void OnBalanceChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectIIIModel", Name="tblAdmin")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblAdmin : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblAdmin object.
        /// </summary>
        /// <param name="adminID">Initial value of the AdminID property.</param>
        /// <param name="adminRole">Initial value of the AdminRole property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static tblAdmin CreatetblAdmin(global::System.Int32 adminID, global::System.String adminRole, global::System.String firstName, global::System.String lastName, global::System.DateTime dateOfBirth, global::System.String phone, global::System.String email, global::System.String userName, global::System.String password)
        {
            tblAdmin tblAdmin = new tblAdmin();
            tblAdmin.AdminID = adminID;
            tblAdmin.AdminRole = adminRole;
            tblAdmin.FirstName = firstName;
            tblAdmin.LastName = lastName;
            tblAdmin.DateOfBirth = dateOfBirth;
            tblAdmin.Phone = phone;
            tblAdmin.Email = email;
            tblAdmin.UserName = userName;
            tblAdmin.Password = password;
            return tblAdmin;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdminID
        {
            get
            {
                return _AdminID;
            }
            set
            {
                if (_AdminID != value)
                {
                    OnAdminIDChanging(value);
                    ReportPropertyChanging("AdminID");
                    _AdminID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AdminID");
                    OnAdminIDChanged();
                }
            }
        }
        private global::System.Int32 _AdminID;
        partial void OnAdminIDChanging(global::System.Int32 value);
        partial void OnAdminIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AdminRole
        {
            get
            {
                return _AdminRole;
            }
            set
            {
                OnAdminRoleChanging(value);
                ReportPropertyChanging("AdminRole");
                _AdminRole = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AdminRole");
                OnAdminRoleChanged();
            }
        }
        private global::System.String _AdminRole;
        partial void OnAdminRoleChanging(global::System.String value);
        partial void OnAdminRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.DateTime _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTime value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectIIIModel", Name="tblImage")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblImage : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblImage object.
        /// </summary>
        /// <param name="imageID">Initial value of the ImageID property.</param>
        /// <param name="imageName">Initial value of the ImageName property.</param>
        public static tblImage CreatetblImage(global::System.Int32 imageID, global::System.String imageName)
        {
            tblImage tblImage = new tblImage();
            tblImage.ImageID = imageID;
            tblImage.ImageName = imageName;
            return tblImage;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageID
        {
            get
            {
                return _ImageID;
            }
            set
            {
                if (_ImageID != value)
                {
                    OnImageIDChanging(value);
                    ReportPropertyChanging("ImageID");
                    _ImageID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ImageID");
                    OnImageIDChanged();
                }
            }
        }
        private global::System.Int32 _ImageID;
        partial void OnImageIDChanging(global::System.Int32 value);
        partial void OnImageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageName
        {
            get
            {
                return _ImageName;
            }
            set
            {
                OnImageNameChanging(value);
                ReportPropertyChanging("ImageName");
                _ImageName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageName");
                OnImageNameChanged();
            }
        }
        private global::System.String _ImageName;
        partial void OnImageNameChanging(global::System.String value);
        partial void OnImageNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectIIIModel", "FK_tblOrderDetails_tblImages", "tblOrderDetails")]
        public EntityCollection<tblOrderDetail> tblOrderDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblOrderDetail>("ProjectIIIModel.FK_tblOrderDetails_tblImages", "tblOrderDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblOrderDetail>("ProjectIIIModel.FK_tblOrderDetails_tblImages", "tblOrderDetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectIIIModel", Name="tblOrder")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblOrder : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblOrder object.
        /// </summary>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="dateOfOrder">Initial value of the DateOfOrder property.</param>
        /// <param name="dateOfAssign">Initial value of the DateOfAssign property.</param>
        /// <param name="totalPrice">Initial value of the TotalPrice property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="directoryName">Initial value of the DirectoryName property.</param>
        /// <param name="paytype">Initial value of the Paytype property.</param>
        /// <param name="creditCard">Initial value of the CreditCard property.</param>
        /// <param name="receiver">Initial value of the Receiver property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        public static tblOrder CreatetblOrder(global::System.Int32 orderID, global::System.Int32 userID, global::System.DateTime dateOfOrder, global::System.DateTime dateOfAssign, global::System.Double totalPrice, global::System.Boolean status, global::System.String directoryName, global::System.String paytype, global::System.Int64 creditCard, global::System.String receiver, global::System.String phone)
        {
            tblOrder tblOrder = new tblOrder();
            tblOrder.OrderID = orderID;
            tblOrder.UserID = userID;
            tblOrder.DateOfOrder = dateOfOrder;
            tblOrder.DateOfAssign = dateOfAssign;
            tblOrder.TotalPrice = totalPrice;
            tblOrder.Status = status;
            tblOrder.DirectoryName = directoryName;
            tblOrder.Paytype = paytype;
            tblOrder.CreditCard = creditCard;
            tblOrder.Receiver = receiver;
            tblOrder.Phone = phone;
            return tblOrder;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfOrder
        {
            get
            {
                return _DateOfOrder;
            }
            set
            {
                OnDateOfOrderChanging(value);
                ReportPropertyChanging("DateOfOrder");
                _DateOfOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfOrder");
                OnDateOfOrderChanged();
            }
        }
        private global::System.DateTime _DateOfOrder;
        partial void OnDateOfOrderChanging(global::System.DateTime value);
        partial void OnDateOfOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfAssign
        {
            get
            {
                return _DateOfAssign;
            }
            set
            {
                OnDateOfAssignChanging(value);
                ReportPropertyChanging("DateOfAssign");
                _DateOfAssign = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfAssign");
                OnDateOfAssignChanged();
            }
        }
        private global::System.DateTime _DateOfAssign;
        partial void OnDateOfAssignChanging(global::System.DateTime value);
        partial void OnDateOfAssignChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double TotalPrice
        {
            get
            {
                return _TotalPrice;
            }
            set
            {
                OnTotalPriceChanging(value);
                ReportPropertyChanging("TotalPrice");
                _TotalPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPrice");
                OnTotalPriceChanged();
            }
        }
        private global::System.Double _TotalPrice;
        partial void OnTotalPriceChanging(global::System.Double value);
        partial void OnTotalPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Boolean _Status;
        partial void OnStatusChanging(global::System.Boolean value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DirectoryName
        {
            get
            {
                return _DirectoryName;
            }
            set
            {
                OnDirectoryNameChanging(value);
                ReportPropertyChanging("DirectoryName");
                _DirectoryName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DirectoryName");
                OnDirectoryNameChanged();
            }
        }
        private global::System.String _DirectoryName;
        partial void OnDirectoryNameChanging(global::System.String value);
        partial void OnDirectoryNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Paytype
        {
            get
            {
                return _Paytype;
            }
            set
            {
                OnPaytypeChanging(value);
                ReportPropertyChanging("Paytype");
                _Paytype = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Paytype");
                OnPaytypeChanged();
            }
        }
        private global::System.String _Paytype;
        partial void OnPaytypeChanging(global::System.String value);
        partial void OnPaytypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 CreditCard
        {
            get
            {
                return _CreditCard;
            }
            set
            {
                OnCreditCardChanging(value);
                ReportPropertyChanging("CreditCard");
                _CreditCard = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreditCard");
                OnCreditCardChanged();
            }
        }
        private global::System.Int64 _CreditCard;
        partial void OnCreditCardChanging(global::System.Int64 value);
        partial void OnCreditCardChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Receiver
        {
            get
            {
                return _Receiver;
            }
            set
            {
                OnReceiverChanging(value);
                ReportPropertyChanging("Receiver");
                _Receiver = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Receiver");
                OnReceiverChanged();
            }
        }
        private global::System.String _Receiver;
        partial void OnReceiverChanging(global::System.String value);
        partial void OnReceiverChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectIIIModel", "FK_tblOrder_tblUser", "tblUser")]
        public tblUser tblUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUser>("ProjectIIIModel.FK_tblOrder_tblUser", "tblUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUser>("ProjectIIIModel.FK_tblOrder_tblUser", "tblUser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblUser> tblUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblUser>("ProjectIIIModel.FK_tblOrder_tblUser", "tblUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblUser>("ProjectIIIModel.FK_tblOrder_tblUser", "tblUser", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectIIIModel", "FK_tblOrderDetails_tblOrder", "tblOrderDetails")]
        public EntityCollection<tblOrderDetail> tblOrderDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblOrderDetail>("ProjectIIIModel.FK_tblOrderDetails_tblOrder", "tblOrderDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblOrderDetail>("ProjectIIIModel.FK_tblOrderDetails_tblOrder", "tblOrderDetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectIIIModel", Name="tblOrderDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblOrderDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblOrderDetail object.
        /// </summary>
        /// <param name="imageID">Initial value of the ImageID property.</param>
        /// <param name="orderID">Initial value of the OrderID property.</param>
        /// <param name="sizeType">Initial value of the SizeType property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        public static tblOrderDetail CreatetblOrderDetail(global::System.Int32 imageID, global::System.Int32 orderID, global::System.Int32 sizeType, global::System.Int32 number)
        {
            tblOrderDetail tblOrderDetail = new tblOrderDetail();
            tblOrderDetail.ImageID = imageID;
            tblOrderDetail.OrderID = orderID;
            tblOrderDetail.SizeType = sizeType;
            tblOrderDetail.Number = number;
            return tblOrderDetail;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageID
        {
            get
            {
                return _ImageID;
            }
            set
            {
                if (_ImageID != value)
                {
                    OnImageIDChanging(value);
                    ReportPropertyChanging("ImageID");
                    _ImageID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ImageID");
                    OnImageIDChanged();
                }
            }
        }
        private global::System.Int32 _ImageID;
        partial void OnImageIDChanging(global::System.Int32 value);
        partial void OnImageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SizeType
        {
            get
            {
                return _SizeType;
            }
            set
            {
                if (_SizeType != value)
                {
                    OnSizeTypeChanging(value);
                    ReportPropertyChanging("SizeType");
                    _SizeType = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SizeType");
                    OnSizeTypeChanged();
                }
            }
        }
        private global::System.Int32 _SizeType;
        partial void OnSizeTypeChanging(global::System.Int32 value);
        partial void OnSizeTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                if (_Number != value)
                {
                    OnNumberChanging(value);
                    ReportPropertyChanging("Number");
                    _Number = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Number");
                    OnNumberChanged();
                }
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectIIIModel", "FK_tblOrderDetails_tblImages", "tblImages")]
        public tblImage tblImage
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblImage>("ProjectIIIModel.FK_tblOrderDetails_tblImages", "tblImages").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblImage>("ProjectIIIModel.FK_tblOrderDetails_tblImages", "tblImages").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblImage> tblImageReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblImage>("ProjectIIIModel.FK_tblOrderDetails_tblImages", "tblImages");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblImage>("ProjectIIIModel.FK_tblOrderDetails_tblImages", "tblImages", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectIIIModel", "FK_tblOrderDetails_tblOrder", "tblOrder")]
        public tblOrder tblOrder
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOrder>("ProjectIIIModel.FK_tblOrderDetails_tblOrder", "tblOrder").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOrder>("ProjectIIIModel.FK_tblOrderDetails_tblOrder", "tblOrder").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblOrder> tblOrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblOrder>("ProjectIIIModel.FK_tblOrderDetails_tblOrder", "tblOrder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblOrder>("ProjectIIIModel.FK_tblOrderDetails_tblOrder", "tblOrder", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectIIIModel", "FK_tblOrderDetails_tblSize", "tblSize")]
        public tblSize tblSize
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSize>("ProjectIIIModel.FK_tblOrderDetails_tblSize", "tblSize").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSize>("ProjectIIIModel.FK_tblOrderDetails_tblSize", "tblSize").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblSize> tblSizeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblSize>("ProjectIIIModel.FK_tblOrderDetails_tblSize", "tblSize");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblSize>("ProjectIIIModel.FK_tblOrderDetails_tblSize", "tblSize", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectIIIModel", Name="tblSize")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSize : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSize object.
        /// </summary>
        /// <param name="sizeType">Initial value of the SizeType property.</param>
        /// <param name="minSize">Initial value of the MinSize property.</param>
        /// <param name="maxSize">Initial value of the MaxSize property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        public static tblSize CreatetblSize(global::System.Int32 sizeType, global::System.Double minSize, global::System.Double maxSize, global::System.Double price)
        {
            tblSize tblSize = new tblSize();
            tblSize.SizeType = sizeType;
            tblSize.MinSize = minSize;
            tblSize.MaxSize = maxSize;
            tblSize.Price = price;
            return tblSize;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SizeType
        {
            get
            {
                return _SizeType;
            }
            set
            {
                if (_SizeType != value)
                {
                    OnSizeTypeChanging(value);
                    ReportPropertyChanging("SizeType");
                    _SizeType = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SizeType");
                    OnSizeTypeChanged();
                }
            }
        }
        private global::System.Int32 _SizeType;
        partial void OnSizeTypeChanging(global::System.Int32 value);
        partial void OnSizeTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double MinSize
        {
            get
            {
                return _MinSize;
            }
            set
            {
                OnMinSizeChanging(value);
                ReportPropertyChanging("MinSize");
                _MinSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinSize");
                OnMinSizeChanged();
            }
        }
        private global::System.Double _MinSize;
        partial void OnMinSizeChanging(global::System.Double value);
        partial void OnMinSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double MaxSize
        {
            get
            {
                return _MaxSize;
            }
            set
            {
                OnMaxSizeChanging(value);
                ReportPropertyChanging("MaxSize");
                _MaxSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxSize");
                OnMaxSizeChanged();
            }
        }
        private global::System.Double _MaxSize;
        partial void OnMaxSizeChanging(global::System.Double value);
        partial void OnMaxSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Double _Price;
        partial void OnPriceChanging(global::System.Double value);
        partial void OnPriceChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectIIIModel", "FK_tblOrderDetails_tblSize", "tblOrderDetails")]
        public EntityCollection<tblOrderDetail> tblOrderDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblOrderDetail>("ProjectIIIModel.FK_tblOrderDetails_tblSize", "tblOrderDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblOrderDetail>("ProjectIIIModel.FK_tblOrderDetails_tblSize", "tblOrderDetails", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ProjectIIIModel", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblUser object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="dateOfBirth">Initial value of the DateOfBirth property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        /// <param name="phone">Initial value of the Phone property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static tblUser CreatetblUser(global::System.Int32 userID, global::System.String firstName, global::System.String lastName, global::System.DateTime dateOfBirth, global::System.String address, global::System.String phone, global::System.String email, global::System.String userName, global::System.String password)
        {
            tblUser tblUser = new tblUser();
            tblUser.UserID = userID;
            tblUser.FirstName = firstName;
            tblUser.LastName = lastName;
            tblUser.DateOfBirth = dateOfBirth;
            tblUser.Address = address;
            tblUser.Phone = phone;
            tblUser.Email = email;
            tblUser.UserName = userName;
            tblUser.Password = password;
            return tblUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateOfBirth
        {
            get
            {
                return _DateOfBirth;
            }
            set
            {
                OnDateOfBirthChanging(value);
                ReportPropertyChanging("DateOfBirth");
                _DateOfBirth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateOfBirth");
                OnDateOfBirthChanged();
            }
        }
        private global::System.DateTime _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTime value);
        partial void OnDateOfBirthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ProjectIIIModel", "FK_tblOrder_tblUser", "tblOrder")]
        public EntityCollection<tblOrder> tblOrders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblOrder>("ProjectIIIModel.FK_tblOrder_tblUser", "tblOrder");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblOrder>("ProjectIIIModel.FK_tblOrder_tblUser", "tblOrder", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
